### ISSUE TITLE
Issue with adding sex feature into model

### ISSUE THREAD

**Issue by kphaterp** [UBC-MDS/abalone_age_classification#51]
I believe there is an issue with adding the feature, Sex, into the model. One of the categories of Sex is Infant (I). It doesn't really make sense for our model to be predicting age if we are already given that the abalone is an Infant from the Sex column. I propose that we drop this feature either for this Milestone or in the future. We should add this as a limitation to the report if we are to include this feature in this Milestone.

Additionally, the train.csv file contains one observation where Sex = 0. This might be an error when the training data is being saved as a csv file, as the original dataset does not contain any examples where Sex = 0

**Comment by lynnwbl** [comment]
Added discussion on Infant class limitation in report

**Comment by lynnwbl** [comment]
Added justification on rings threshold in the About Data Set section

**Comment by nickmao1994** [comment]
For the sex=0 issue: when we load the data, we need to set header=0 in pd.read_csv to avoid 0,1,2,3,4,5,6,7 in each column. They are default column names.
For sex issue: I think we need to include them into our model because we don't have any domain knowledge on the relationship abalone's sex with their age. We can only infer from the name of the sex. But I agree that we need to add limitation discussion on this issue.
For threshold: I believe on kaggle, someone upload a classification notebook and set the threshold at 11 rings. I think this is quite arbitrary.

**Comment by lynnwbl** [comment]
I believe in historical study, they use three categories. Here is what wrote regarding the threshold: 

> In the research paper "A Quantitative Comparison of Dystal and Backpropagation" that David Clark, Zoltan Schreter and Anthony Adams submitted to the Australian Conference on Neural Networks (ACNN'96), the original abalone data set was treated as a 3-category classification problem (grouping ring classes 1-8, 9 and 10, and 11 on). In our project, we will treat the data set as a 2-categorical classification problem (grouping ring classes less or equal to 11, and more than 11).
