### ISSUE TITLE
Meeting Minutes November 26th

### ISSUE THREAD

**Issue by kphaterp** [UBC-MDS/abalone_age_classification#57]
To do:

- Complete figure captions (Kiran)
- Output dataframe with model performance and interpret model performance (Nick)
- Small description of all the scripts in the README file (Rakesh)
- Create proposal.md file and make the release (Lynn)

Proof-reader: Lynn

**Comment by veerupandey** [comment]
Update script usage in README. 
https://github.com/UBC-MDS/abalone_age_classification/pull/60

**Comment by lynnwbl** [comment]
- proposal.md file created and saved under docs/
- Overwrite proposal section on README file according to Milestone 2 requirements
- fix link to Milestone 2 Report on README file
- Removed EDA figures from the EDA section on README file since we already have a link that points to the detailed EDA file

**Comment by nickmao1994** [comment]
- update test script to include an output table
- add train and test plots to Milestone 2 Report
- add model interpretation to the report
